services:
#  app:
#    build: ./
#    ports:
#      - 3000:3000
#    volumes:
#      - .:/home/node/app
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data: